### ISSUE TITLE
Error: EMAXBUFFER

### ISSUE THREAD

**Issue by oprince** [mikermcneil/skipper-memory#1]
File upload ends with the below pasted error, after 1 or 2 successful uploads with skipper-memory:

`"Error: EMAXBUFFER: An Upstream (`NOOP_image`) timed out before it was plugg
ed into a receiver. It was still unused after waiting 4500ms. You can configure
this timeout by changing the `maxTimeToBuffer` option.",
    "    at null.<anonymous> (C:\\projects\\dependancies\\node_modules\\skipper\
\standalone\\Upstream\\Upstream.js:86:15)",
    "    at Timer.listOnTimeout (timers.js:92:15)"`

All uploads are identical and do include the attached file. The problem seems to be related to insufficient stream closure procedure of a successful upload.

versions:
======
node.js: 4.5
skipper: 0.8.2
skipper-memory: 0.0.3

Any help would be much appreciated !
Thanks!

**Comment by Brendan92** [comment]
@oprince Did you find any solution to this? 

Getting this on upload larger than 70kb:

Unable to parse HTTP body- error occurred :: ‘Error: EMAXBUFFER: An Upstream (file) timed out before it was plugged into a receiver. It was still unused after waiting 4500ms. You can configure this timeout by changing the maxTimeToBuffer option.\n at Timeout._onTimeout (/backend/node_modules/skipper/standalone/Upstream/Upstream.js:86:15)\n at ontimeout (timers.js:475:11)\n at tryOnTimeout (timers.js:310:5)\n at Timer.listOnTimeout (timers.js:270:5)’

Please help me solve this.
